<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="NITRO-5-1109" name="pytest" skipped="6" tests="16" time="0.075" timestamp="2022-03-29T17:00:08.325173"><testcase classname="test_calculator" name="test_add[3-2-5]" time="0.001"><skipped message="unconditional skip" type="pytest.skip">C:\Users\shobh\PycharmProjects\Pytestcalci\test_calculator.py:4: unconditional skip</skipped></testcase><testcase classname="test_calculator" name="test_add[4-2-6]" time="0.000"><skipped message="unconditional skip" type="pytest.skip">C:\Users\shobh\PycharmProjects\Pytestcalci\test_calculator.py:4: unconditional skip</skipped></testcase><testcase classname="test_calculator" name="test_add[5-5-10]" time="0.000"><skipped message="unconditional skip" type="pytest.skip">C:\Users\shobh\PycharmProjects\Pytestcalci\test_calculator.py:4: unconditional skip</skipped></testcase><testcase classname="test_calculator" name="test_add[5-5-9]" time="0.000"><skipped message="unconditional skip" type="pytest.skip">C:\Users\shobh\PycharmProjects\Pytestcalci\test_calculator.py:4: unconditional skip</skipped></testcase><testcase classname="test_calculator" name="test_sub[3-2-1]" time="0.001" /><testcase classname="test_calculator" name="test_sub[4-2-2]" time="0.001" /><testcase classname="test_calculator" name="test_sub[5-5-0]" time="0.001" /><testcase classname="test_calculator" name="test_sub[5-5-9]" time="0.001"><skipped message="" type="pytest.xfail" /></testcase><testcase classname="test_calculator" name="test_mult[3-2-6]" time="0.001" /><testcase classname="test_calculator" name="test_mult[4-2-8]" time="0.001" /><testcase classname="test_calculator" name="test_mult[5-5-25]" time="0.001" /><testcase classname="test_calculator" name="test_mult[5-5-9]" time="0.001"><failure message="assert 25 == 9">a = 5, b = 5, c = 9

    @pytest.mark.parametrize("a,b,c",[(3,2,6),(4,2,8),(5,5,25),(5,5,9)])
    def test_mult(a,b,c):
        r=calculator.mult(a, b)
&gt;       assert r == c
E       assert 25 == 9

test_calculator.py:21: AssertionError</failure></testcase><testcase classname="test_calculator" name="test_div[3-2-1.5]" time="0.001" /><testcase classname="test_calculator" name="test_div[4-2-2]" time="0.001" /><testcase classname="test_calculator" name="test_div[5-5-1]" time="0.001" /><testcase classname="test_calculator" name="test_div[5-5-9]" time="0.001"><skipped message="" type="pytest.xfail" /></testcase></testsuite></testsuites>